# Generated by Django 4.1 on 2023-09-04 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "пост", "verbose_name_plural": "Пости"},
        ),
        migrations.AddField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 4, 8, 34, 10, 505330, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
